---
title: "Check BCC06 problem of copyKat"
output: html_document
date: "2024-06-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(Seurat)
library(ggplot2)

```

## Load BCC06 dataset and create a Seurat object


```{r}
data_path<-"~/Documents/CNV_RNAseq_benchmark/data/BCC_processed_matrices/"
#Load dataset
meta_data <- fread(paste0(data_path,"GSE123813_bcc_all_metadata.txt.gz"))

count_matrix<-fread(paste0(data_path,"GSE123813_bcc_scRNA_counts.txt.gz"))
gene_names<-count_matrix$V1
count_matrix$V1<-NULL
count_matrix<-as.matrix(count_matrix)
row.names(count_matrix)<-gene_names

#Cluster BCC06 pre alone
meta_data<-meta_data[meta_data$treatment=="pre" & meta_data$patient=="su006",]

#Add copyKat annotations
copykat_pred<-fread("../snakemake_pipeline/results/output_BCC06/copykat/BCC06_copykat_prediction.txt")

meta_data$barcode<-paste0(gsub(".*_","",meta_data$cell.id),"-1")
meta_data<-merge(meta_data,copykat_pred,by.x="barcode",by.y="cell.names",all.x=TRUE)
meta_data$copykat.pred[is.na(meta_data$copykat.pred)]<-"unknown"

table(meta_data$cluster,meta_data$copykat.pred)

#Filter count matrix
count_matrix<-count_matrix[,meta_data$cell.id]

#Check previous annotations
input_copykat<-fread(paste0(data_path,"input_BCC06/sample_annotation.txt"),
                     header=FALSE)
table(input_copykat$V2)

#No matching on the barcode directly possible because data was first FACSsorted
#(same barcode is multiple times in the dataset)
#meta_data$input_copykat<-ifelse(meta_data$barcode %in% input_copykat$V1,TRUE,FALSE)
meta_data$input_copykat<-meta_data$cluster %in% c("Endothelial","Melanocytes",
                                              "Myofibroblasts","Tumor_1","Tumor_2")
input_copykat2<-fread(paste0(data_path,"input_BCC06post/sample_annotation.txt"),
                     header=FALSE)
table(input_copykat2$V2)

input_copykat3<-fread("../snakemake_pipeline/data/input_MM/sample_annotation.txt",
                     header=FALSE)
table(input_copykat3$V2)

```

## Check UMAP from paper

```{r}
ggplot(meta_data,aes(x=UMAP1,y=UMAP2,color=cluster))+
  geom_point(aes(alpha=ifelse(input_copykat,1,0.2)))+
  guides(alpha="none")

ggplot(meta_data,aes(x=UMAP1,y=UMAP2,color=copykat.pred))+
  geom_point(aes(alpha=ifelse(input_copykat,1,0.2)))+
  guides(alpha="none")

```

